# Generated by Django 3.2.4 on 2021-11-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('block_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesflatpage',
            name='product_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.product'),
        ),
    ]
