# Generated by Django 3.2.4 on 2021-11-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_page', '0003_auto_20211130_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='showslideblock',
            name='publications_slide',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='publish slide photo'),
        ),
        migrations.AddField(
            model_name='slidesflatpage',
            name='publications_slide',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='publish slide photo'),
        ),
    ]
