# Generated by Django 3.2.4 on 2021-11-28 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('sender_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='sender deleted at')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='recipient deleted at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umessages.message', verbose_name='message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'recipient',
                'verbose_name_plural': 'recipients',
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umessages.message', verbose_name='latest message')),
                ('um_from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_from_users', to=settings.AUTH_USER_MODEL, verbose_name='from user')),
                ('um_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_to_users', to=settings.AUTH_USER_MODEL, verbose_name='to user')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', through='umessages.MessageRecipient', to=settings.AUTH_USER_MODEL, verbose_name='recipients'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AddConstraint(
            model_name='messagecontact',
            constraint=models.UniqueConstraint(fields=('um_from_user', 'um_to_user'), name='latestmessage'),
        ),
    ]
